# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.1.2"

gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => :development
gem 'minitest'
gem 'mocha'
