require 'rake/testtask'

task :sorbet do |t|
  sh "srb typecheck"
end

Rake::TestTask.new(:test) do |t|
  t.libs << "."
  t.options = "-p"
  t.test_files = FileList['*_test.rb']
end
task :test => :sorbet

task :default => :test
